# Generated by Django 3.2.6 on 2021-08-26 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_rename_usuario_quizusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntasrespondidas',
            old_name='usuario',
            new_name='quizUser',
        ),
    ]
